# Generated by Django 4.2.4 on 2023-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('ceo', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='foodprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('manufact_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
